// Filename: fs_PrintResultPrivateImpl.cpp
//
// Project: Horizon

#include <nn/Result.h>
#include <nn/fs/fs_Result.h>


#define BEGIN_GET_RESULT_DESCRIPTION_STRING_IMPL \
    const char* GetResultPrivateDescriptionStringImpl(nn::Result result) \
    { \
        (void)result; \
        if (0) {}

#define CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(nameSpace, description) \
        else if (result.GetDescription() == nameSpace::description) return #description;

#define END_GET_RESULT_DESCRIPTION_STRING_IMPL \
        return 0; \
    }

namespace nn {
namespace fs {
namespace detail {

BEGIN_GET_RESULT_DESCRIPTION_STRING_IMPL
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_FIND_FINISHED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_DBM_FIND_FINISHED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_DBM_FIND_KEY_FINISHED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_DBM_ITERATION_FINISHED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_NOT_FOUND)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_ARCHIVE_NOT_FOUND)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_CARD_PATITION_NOT_FOUND)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_DBM_NOT_FOUND)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_DBM_KEY_NOT_FOUND)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_DBM_FILE_NOT_FOUND)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_DBM_DIRECTORY_NOT_FOUND)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_DBM_ID_NOT_FOUND)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_FAT_NOT_FOUND)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_MEDIA_NOT_FOUND)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_FAT_NO_STORAGE)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_CARD_ROM_NOT_FOUND)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_CARD_ROM_NO_DEVICE)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_CARD_ROM_UNKNOWN)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_CARD_BACKUP_NOT_FOUND)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_CARD_BACKUP_TYPE1_NO_DEVICE)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_CARD_BACKUP_TYPE2_NO_DEVICE)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_CARD_BACKUP_TYPE1_UNKNOWN)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_CARD_BACKUP_TYPE2_UNKNOWN)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_SDMC_NOT_FOUND)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_SDMC_NO_DEVICE)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_SDMC_UNKNOWN)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_ALREADY_EXISTS)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_DBM_ALREADY_EXISTS)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_FAT_ALREADY_EXISTS)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_NOT_ENOUGH_SPACE)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_DBM_NOT_ENOUGH_SPACE)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_FAT_NOT_ENOUGH_SPACE)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_ARCHIVE_INVALIDATED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_OPERATION_DENIED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_RESOURCE_LOCKED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_CACHE_ERROR)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_DBM_OPERATION_DENIED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_FAT_OPERATION_DENIED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_WRITE_PROTECTED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_SDMC_WRITE_PROTECTED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_CARD_ROM_WRITE_PROTECTED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_MEDIA_ACCESS_ERROR)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_CARD_ROM_ACCESS_ERROR)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_CARD_ROM_COMM_ERROR)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_CARD_BACKUP_COMM_ERROR)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_CARD_BACKUP_TYPE1_COMM_ERROR)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_CARD_BACKUP_TYPE2_COMM_ERROR)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_NAND_ACCESS_ERROR)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_NAND_COMM_ERROR)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_NAND_ECC_FAILED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_SDMC_ACCESS_ERROR)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_SDMC_COMM_ERROR)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_SDMC_ECC_FAILED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_BACKUP_NOT_REQUIRED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_NOT_FORMATTED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_FORMAT_IS_FACTORY_DEFAULTS)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_DBM_NOT_FORMATTED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_DBM_VERSION_MISMATCH)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_BAD_FORMAT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_FAT_BAD_FORMAT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_FAT_BROKEN_ENTRY)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_CARD_BACKUP_BAD_FORMAT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_CARD_BACKUP_TYPE1_BAD_FORMAT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_CARD_BACKUP_TYPE2_BAD_FORMAT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_VERIFICATION_FAILED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_HASH_MISMATCH)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_VERIFY_SIGNATURE_FAILED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_INVALID_FILE_FORMAT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_VERIFY_HEADER_MAC_FAILED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_VERIFY_DATA_HASH_FAILED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_PROGRAM_DATA_NOT_FOUND)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_PROGRAM_NOT_FOUND)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_SYSTEM_MENU_DATA_NOT_FOUND)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_BANNER_DATA_NOT_FOUND)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_LOGO_DATA_NOT_FOUND)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_PROGRAM_INFO_NOT_FOUND)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_CONTENT_NOT_FOUND)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_NO_SUCH_EXEFS_SECTION)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_REQUEST_RETRY)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_REQUEST_SAME_RETRY)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_REQUEST_SMALL_RETRY)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_INVALID_PROGRAM_FORMAT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_INVALID_CXI_FORMAT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_INVALID_CCI_FORMAT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_OUT_OF_RESOURCE)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_OUT_OF_MEMORY)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_HANDLE_TABLE_FULL)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_DBM_OUT_OF_RESOURCE)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_DBM_TABLE_FULL)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_DBM_FILE_ENTRY_FULL)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_DBM_DIRECTORY_ENTRY_FULL)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_DBM_OUT_OF_MEMORY)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_FAT_OUT_OF_RESOURCE)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_FAT_OUT_OF_MEMORY)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_ACCESS_DENIED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_NOT_DEVELOPMENT_ID)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_NO_CONTENT_RIGHTS)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_DBM_ACCESS_DENIED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_FAT_ACCESS_DENIED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_INVALID_ARGUMENT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_INVALID_POSITION_BASE)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_INVALID_PATH_FORMAT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_PATH_TOO_LONG)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_OUT_OF_BOUNDS)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_INVALID_POSITION)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_DBM_INVALID_ARGUMENT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_DBM_FILE_NAME_TOO_LONG)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_DBM_DIRECTORY_NAME_TOO_LONG)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_DBM_INVALID_PATH_FORMAT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_DBM_OUT_OF_BOUNDS)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_FAT_INVALID_ARGUMENT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_FAT_INVALID_SIZE)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_NOT_INITIALIZED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_LIBRARY_NOT_INITIALIZED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_MOVABLE_DATA_IS_NOT_ENABLED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_DBM_NOT_INITIALIZED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_CARD_ROM_NOT_INITIALIZED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_ALREADY_INITIALIZED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_UNSUPPORTED_OPERATION)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_UNSUPPORTED_ALIGNMENT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_UNSUPPORTED_MEDIA)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_DBM_INVALID_OPERATION)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_NOT_IMPLEMENTED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_INVALID_KEY_TYPE)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_PARTITION_NOT_FOUND)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_FAT_ERROR)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_FAT_CORRUPTION)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_NAND_ERROR)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_NAND_FATAL)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::fs, DESCRIPTION_UNKNOWN_ERROR)
END_GET_RESULT_DESCRIPTION_STRING_IMPL

void GetResultPrivateDescriptionStringImplKeeper()
{
    const char* (*volatile f)(nn::Result) = GetResultPrivateDescriptionStringImpl;
}

} // namespace detail
} // namespace fs
} // namespace nn