#pragma once

#define NN_OS_ADDR_SIZE(name)   (name ## _END - name ## _BEGIN)

#define NN_OS_ADDR_SPACE_BEGIN  0x00000000
#define NN_OS_ADDR_SPACE_END    0x20000000

#define NN_OS_ADDR_NULL_TRAP_BEGIN  NN_OS_ADDR_SPACE_BEGIN
#define NN_OS_ADDR_NULL_TRAP_END    NN_OS_ADDR_CODE_BEGIN
#define NN_OS_ADDR_NULL_TRAP_SIZE   NN_OS_ADDR_SIZE(NN_OS_ADDR_NULL_TRAP)

#define NN_OS_ADDR_CODE_BEGIN       0x00100000
#define NN_OS_ADDR_CODE_END         NN_OS_ADDR_LAND_BEGIN
#define NN_OS_ADDR_CODE_SIZE        NN_OS_ADDR_SIZE(NN_OS_ADDR_CODE)

#define NN_OS_ADDR_READONLY_SHARED_PAGE     0x1FF80000
#define NN_OS_ADDR_WRITABLE_SHARED_PAGE     0x1FF81000
