#pragma once

#include "jpeg_MpTypesInternal.h"

#ifdef __cplusplus

namespace nn {
namespace jpeg {
namespace CTR {

const u32 JPEG_ENCODER_THUMBNAIL_QUALITY = 70;

const u32 JPEG_ENCODER_THUMBNAIL_INPUT_BUFFER_WIDTH = 16;
const u32 JPEG_ENCODER_THUMBNAIL_INPUT_BUFFER_HEIGHT = 16;

typedef u8 JpegMpEncoderDqTableType;
typedef s16 JpegMpEncoderQTableType;
typedef s16 JpegMpEncoderYCbCrType;

const u32 NUM_JPEG_ENCODER_COMPONENTS = 3;
const u32 NUM_JPEG_ENCODER_Q_TBLS = 2;
const u32 NUM_JPEG_ENCODER_Q_TBL_ELEMS = 64;

const u32 JPEG_ENCODER_MAX_HUFFMAN_CODE_LENGTH = 16;
const u32 JPEG_ENCODER_MAX_NUMBER_OF_HUFFMAN_CODES = 256;

struct JpegMpEncoderHuffmanStructure
{

    u8 mEhufsi[260];
    u32 mEhufco[258];
};

struct JpegMpEncoderComponentStructure
{
    s16 mCoefficients[64];
    s32 mLastDcValue;
    JpegMpEncoderHuffmanStructure* mDcTable;
    JpegMpEncoderHuffmanStructure* mAcTable;
};

#ifdef JPEG_ENCODER_USE_DHT_CACHE
#else

union JpegMpEncoderHuffmanEncoderBuildTableWork
{
    struct
    {
        u16 huffCodes[JPEG_ENCODER_MAX_NUMBER_OF_HUFFMAN_CODES];
        u8 huffSizes[JPEG_ENCODER_MAX_NUMBER_OF_HUFFMAN_CODES];
    } s;
    u32 force_structure_alignment;
};
#endif

struct JpegMpEncoderConvertToYuvFuncWork
{
    JpegMpEncoderYCbCrType yBuf[64 * 4];
    JpegMpEncoderYCbCrType cbBuf[64];
    JpegMpEncoderYCbCrType crBuf[64];
};

struct JpegMpEncoderContext;
typedef void (*JpegMpEncoderConvertToYuvFunc)(JpegMpEncoderContext* pCtx, u32 col, u32 row);

struct JpegMpEncoderContext
{
    JpegMpEncoderConvertToYuvFuncWork convWork;
    JpegMpEncoderConvertToYuvFunc convFunc;
    u8 loops;
    u8 mcu_cols;
    u8 mcu_rows;
    u8 omitDht;
    const void* pSrc;
    u16 width;
    u16 height;
    u8* pDst;

    u32 dstOffset;
    u32 writeLimit;
    u32 bitCode;

    u8 bitLen;
    u8 quality;
    u8 samplingX;
    u8 samplingY;

    s8 errorCode;
    u8 dstPixelSampling;
    u8 srcPixelFormat;
    u8 reserved2[1];

    u32 inputBufferWidth;

    JpegMpEncoderConvertToYuvFunc thumbSrcConvFunc;
    void* pThumbDst;
    const void* pThumbSrc;
    u16 thumbSrcWidth;
    u16 thumbSrcHeight;
    u32 thumbSrcInputBufferWidth;

    struct
    {
        s16* du;
        u8* pHufsi;
        u32* pHufco;
        u32 bitLen2;
        u32 bitCode2;
        u8* pDst2;
        u8* pDst2Limit;
        u32 inputBufferWidthM8x2;
        u32 inputBufferWidthM16x2;
        u32 inputBufferWidthM8x3;
        u32 inputBufferWidthM16x3;
        u32 inputBufferWidthM8x4;
        u32 inputBufferWidthM16x4;
        u32 inputBufferWidthX3;
    } asmWork;

    JpegMpEncoderComponentStructure component[NUM_JPEG_ENCODER_COMPONENTS];

#ifdef JPEG_ENCODER_USE_DHT_CACHE
#else
    JpegMpEncoderHuffmanStructure dcTbl[NUM_JPEG_ENCODER_Q_TBLS];
    JpegMpEncoderHuffmanStructure acTbl[NUM_JPEG_ENCODER_Q_TBLS];
#endif

    JpegMpEncoderDqTableType dqBuf[NUM_JPEG_ENCODER_Q_TBLS * NUM_JPEG_ENCODER_Q_TBL_ELEMS];
    JpegMpEncoderQTableType qBuf[NUM_JPEG_ENCODER_Q_TBLS * NUM_JPEG_ENCODER_Q_TBL_ELEMS];
};

enum JpegMpEncoderApp1TagIndex
{

    JPEG_ENCODER_APP1_TAG_INDEX_IFD0_MAKE = 0,
    JPEG_ENCODER_APP1_TAG_INDEX_IFD0_MODEL,
    JPEG_ENCODER_APP1_TAG_INDEX_IFD0_ORIENTATION,
    JPEG_ENCODER_APP1_TAG_INDEX_IFD0_X_RESOLUTION,
    JPEG_ENCODER_APP1_TAG_INDEX_IFD0_Y_RESOLUTION,
    JPEG_ENCODER_APP1_TAG_INDEX_IFD0_RESOLUTION_UNIT,
    JPEG_ENCODER_APP1_TAG_INDEX_IFD0_SOFTWARE,
    JPEG_ENCODER_APP1_TAG_INDEX_IFD0_DATE_TIME,
    JPEG_ENCODER_APP1_TAG_INDEX_IFD0_YCBCR_POSITIONING,
    JPEG_ENCODER_APP1_TAG_INDEX_IFD0_EXIF_IFD_POINTER,
    JPEG_ENCODER_APP1_TAG_INDEX_IFD0_GPS_IFD_POINTER,

    JPEG_ENCODER_APP1_TAG_INDEX_EXIF_VERSION,
    JPEG_ENCODER_APP1_TAG_INDEX_EXIF_DATE_TIME_ORIGINAL,
    JPEG_ENCODER_APP1_TAG_INDEX_EXIF_DATE_TIME_DIGITIZED,
    JPEG_ENCODER_APP1_TAG_INDEX_EXIF_COMPONENTS_CONFIGURATION,
    JPEG_ENCODER_APP1_TAG_INDEX_EXIF_MAKERNOTE,
    JPEG_ENCODER_APP1_TAG_INDEX_EXIF_FLASHPIX_VERSION,
    JPEG_ENCODER_APP1_TAG_INDEX_EXIF_COLOR_SPACE,
    JPEG_ENCODER_APP1_TAG_INDEX_EXIF_PIXEL_X_DIMENSION,
    JPEG_ENCODER_APP1_TAG_INDEX_EXIF_PIXEL_Y_DIMENSION,
    JPEG_ENCODER_APP1_TAG_INDEX_EXIF_INTEROPERABILITY_IFD_POINTER,
    JPEG_ENCODER_APP1_TAG_INDEX_EXIF_IMAGE_UNIQUE_ID,

    JPEG_ENCODER_APP1_TAG_INDEX_MAKERNOTE_TWL_PRIVATE,
    JPEG_ENCODER_APP1_TAG_INDEX_MAKERNOTE_TWL_PHOTO,
    JPEG_ENCODER_APP1_TAG_INDEX_MAKERNOTE_TWL_USER,

    JPEG_ENCODER_APP1_TAG_INDEX_MAKERNOTE_CTR,
    JPEG_ENCODER_APP1_TAG_INDEX_MAKERNOTE_CTR_DUMMY = JPEG_ENCODER_APP1_TAG_INDEX_MAKERNOTE_CTR +
        detail::NUM_MAKER_NOTES - 1,

    JPEG_ENCODER_APP1_TAG_INDEX_INTEROPERABILITY_INDEX,
    JPEG_ENCODER_APP1_TAG_INDEX_INTEROPERABILITY_VERSION,
    JPEG_ENCODER_APP1_TAG_INDEX_INTEROPERABILITY_RELATED_IMAGE_FILE_FORMAT,

    JPEG_ENCODER_APP1_TAG_INDEX_GPS_VERSION_ID,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_LATITUDE_REF,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_LATITUDE,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_LONGITUDE_REF,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_LONGITUDE,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_ALTITUDE_REF,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_ALTITUDE,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_TIME_STAMP,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_SATELLITES,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_STATUS,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_MEASURE_MODE,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_DOP,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_SPEED_REF,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_SPEED,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_TRACK_REF,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_TRACK,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_IMG_DIRECTION_REF,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_IMG_DIRECTION,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_MAP_DATUM,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_DEST_LATITUDE_REF,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_DEST_LATITUDE,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_DEST_LONGITUDE_REF,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_DEST_LONGITUDE,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_DEST_BEARING_REF,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_DEST_BEARING,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_DEST_DISTANCE_REF,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_DEST_DISTANCE,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_PROCESSING_METHOD,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_AREA_INFORMATION,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_DATE_STAMP,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_DIFFERENTIAL,

    JPEG_ENCODER_APP1_TAG_INDEX_THUMB_COMPRESSION,
    JPEG_ENCODER_APP1_TAG_INDEX_THUMB_X_RESOLUTION,
    JPEG_ENCODER_APP1_TAG_INDEX_THUMB_Y_RESOLUTION,
    JPEG_ENCODER_APP1_TAG_INDEX_THUMB_RESOLUTION_UNIT,
    JPEG_ENCODER_APP1_TAG_INDEX_THUMB_JPEG_INTERCHANGE_FORMAT,
    JPEG_ENCODER_APP1_TAG_INDEX_THUMB_JPEG_INTERCHANGE_FORMAT_LENGTH,

    NUM_JPEG_ENCODER_APP1_TAGS,

    JPEG_ENCODER_APP1_TAG_INDEX_IFD0_LOOP_BEGIN = JPEG_ENCODER_APP1_TAG_INDEX_IFD0_MAKE,
    JPEG_ENCODER_APP1_TAG_INDEX_EXIF_LOOP_BEGIN = JPEG_ENCODER_APP1_TAG_INDEX_EXIF_VERSION,
    JPEG_ENCODER_APP1_TAG_INDEX_MAKERNOTE_LOOP_BEGIN = JPEG_ENCODER_APP1_TAG_INDEX_MAKERNOTE_TWL_PRIVATE,
    JPEG_ENCODER_APP1_TAG_INDEX_INTEROPERABILITY_LOOP_BEGIN = JPEG_ENCODER_APP1_TAG_INDEX_INTEROPERABILITY_INDEX,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_LOOP_BEGIN = JPEG_ENCODER_APP1_TAG_INDEX_GPS_VERSION_ID,
    JPEG_ENCODER_APP1_TAG_INDEX_THUMB_LOOP_BEGIN = JPEG_ENCODER_APP1_TAG_INDEX_THUMB_COMPRESSION,

    JPEG_ENCODER_APP1_TAG_INDEX_IFD0_LOOP_END = JPEG_ENCODER_APP1_TAG_INDEX_EXIF_LOOP_BEGIN,
    JPEG_ENCODER_APP1_TAG_INDEX_EXIF_LOOP_END = JPEG_ENCODER_APP1_TAG_INDEX_MAKERNOTE_LOOP_BEGIN,
    JPEG_ENCODER_APP1_TAG_INDEX_MAKERNOTE_LOOP_END = JPEG_ENCODER_APP1_TAG_INDEX_INTEROPERABILITY_LOOP_BEGIN,
    JPEG_ENCODER_APP1_TAG_INDEX_INTEROPERABILITY_LOOP_END = JPEG_ENCODER_APP1_TAG_INDEX_GPS_LOOP_BEGIN,
    JPEG_ENCODER_APP1_TAG_INDEX_GPS_LOOP_END = JPEG_ENCODER_APP1_TAG_INDEX_THUMB_LOOP_BEGIN,
    JPEG_ENCODER_APP1_TAG_INDEX_THUMB_LOOP_END = NUM_JPEG_ENCODER_APP1_TAGS
};

enum App1IfdIndex
{
    APP1_IFD_INDEX_IFD0 = 0,
    APP1_IFD_INDEX_EXIF,
    APP1_IFD_INDEX_MAKERNOTE,
    APP1_IFD_INDEX_INTEROPERABILITY,
    APP1_IFD_INDEX_GPS,
    APP1_IFD_INDEX_THUMB,

    NUM_APP1_IFDS
};

struct JpegMpEncoderIfdWorkObj
{
    u16 count;
    u8 reserved[2];
    size_t offset;
    size_t size;
    u32 offsetToNextIfd;
};

enum JpegMpEncoderApp2TagIndex
{

    JPEG_MP_ENCODER_APP2_TAG_INDEX_MPF_VERSION = 0,
    JPEG_MP_ENCODER_APP2_TAG_INDEX_NUMBER_OF_IMAGES,
    JPEG_MP_ENCODER_APP2_TAG_INDEX_MP_ENTRY,
    JPEG_MP_ENCODER_APP2_TAG_INDEX_IMAGE_UID_LIST,
    JPEG_MP_ENCODER_APP2_TAG_INDEX_TOTAL_FRAMES,

    JPEG_MP_ENCODER_APP2_TAG_INDEX_MPF_VERSION_SPECIAL,
    JPEG_MP_ENCODER_APP2_TAG_INDEX_MP_INDIVIDUAL_NUM,
    JPEG_MP_ENCODER_APP2_TAG_INDEX_PAN_ORIENTATION,
    JPEG_MP_ENCODER_APP2_TAG_INDEX_PAN_OVERLAP_H,
    JPEG_MP_ENCODER_APP2_TAG_INDEX_PAN_OVERLAP_V,
    JPEG_MP_ENCODER_APP2_TAG_INDEX_BASE_VIEWPOINT_NUM,
    JPEG_MP_ENCODER_APP2_TAG_INDEX_CONVERGENCE_ANGLE,
    JPEG_MP_ENCODER_APP2_TAG_INDEX_BASELINE_LENGTH,
    JPEG_MP_ENCODER_APP2_TAG_INDEX_VERTICAL_DIVERGENCE,
    JPEG_MP_ENCODER_APP2_TAG_INDEX_AXIS_DISTANCE_X,
    JPEG_MP_ENCODER_APP2_TAG_INDEX_AXIS_DISTANCE_Y,
    JPEG_MP_ENCODER_APP2_TAG_INDEX_AXIS_DISTANCE_Z,
    JPEG_MP_ENCODER_APP2_TAG_INDEX_YAW_ANGLE,
    JPEG_MP_ENCODER_APP2_TAG_INDEX_PITCH_ANGLE,
    JPEG_MP_ENCODER_APP2_TAG_INDEX_ROLL_ANGLE,

    NUM_JPEG_MP_ENCODER_APP2_TAGS,

    JPEG_MP_ENCODER_APP2_TAG_INDEX_INDEX_LOOP_BEGIN = JPEG_MP_ENCODER_APP2_TAG_INDEX_MPF_VERSION,
    JPEG_MP_ENCODER_APP2_TAG_INDEX_ATTRIBUTE_LOOP_BEGIN = JPEG_MP_ENCODER_APP2_TAG_INDEX_MPF_VERSION_SPECIAL,
    JPEG_MP_ENCODER_APP2_TAG_INDEX_UNDEFINED_LOOP_BEGIN = JPEG_MP_ENCODER_APP2_TAG_INDEX_PAN_ORIENTATION,

    JPEG_MP_ENCODER_APP2_TAG_INDEX_INDEX_LOOP_END = JPEG_MP_ENCODER_APP2_TAG_INDEX_ATTRIBUTE_LOOP_BEGIN,
    JPEG_MP_ENCODER_APP2_TAG_INDEX_ATTRIBUTE_LOOP_END = NUM_JPEG_MP_ENCODER_APP2_TAGS,
    JPEG_MP_ENCODER_APP2_TAG_INDEX_UNDEFINED_LOOP_END = JPEG_MP_ENCODER_APP2_TAG_INDEX_ATTRIBUTE_LOOP_END
};

enum App2MpIndexIfdIndex
{
    APP2_MP_INDEX_IFD_INDEX = 0,
    APP2_MP_INDEX_IFD_INDEX_ATTRIBUTE,

    NUM_APP2_MP_INDEX_IFDS
};

enum App2MpAttributeIfdIndex
{
    APP2_MP_ATTRIBUTE_IFD_INDEX_ATTRIBUTE = 0,

    NUM_APP2_MP_ATTRIBUTE_IFDS
};

union JpegMpEncoderApp2TiffMpEntryObj
{
    u8 data[MP_ENTRY_SIZE];
    struct
    {
        u8 typeInfoLongData[4];
        u8 imageSizeLongData[4];
        u8 imageOffsetLongData[4];
        u8 dependentImage1EntryNumShortData[2];
        u8 dependentImage2EntryNumShortData[2];
    } s;
};

namespace detail
{
struct JpegMpEncoderWorkObj
{

    JpegMpEncoderContext ctx;

    bool useMpFormat;
    bool addThumbnail;
    bool isTiffLittleEndian;
    bool isApp2TiffLittleEndian;

    size_t app1SizeTmp;
    u32 app1ExifIfdPointerData[1];
    u32 app1InteroperabilityIfdPointerData[1];
    u32 app1GpsIfdPointerData[1];
    u32 app1PixelXDimensionData[1];
    u32 app1PixelYDimensionData[1];
    u32 app1JpegInterchangeFormatData[1];
    u32 app1JpegInterchangeFormatLengthData[1];
    u8* pLastTwlPrivateDataBuffer;
    JpegMpEncoderIfdWorkObj app1IfdWork[NUM_APP1_IFDS];
    JpegTagWorkObj app1TagWork[NUM_JPEG_ENCODER_APP1_TAGS];

    JpegMpEncoderApp2TiffMpEntryObj* pApp2MpEntry;
    u8* pApp2MpImageUidList;
    u32 maxNumImages;

    struct
    {

        MpTypeCode typeCode;
        MpTypeCode firstTypeCode;
        u32 numberOfImages;
        u32 curIndex;
        u8* pFirstDst;
        size_t firstSize;
        const char* pImageUid;
        u16 dependentImage1EntryNum;
        u16 dependentImage2EntryNum;
        bool isDependentParent;
        bool isDependentChild;
        bool isRepresentative;
        bool isRepresentativeSet;
        bool addImageUidList;
        bool addTotalFrames;
        bool isBaseline;
        bool omitPixelDimensions;
        u32 numberOfImagesData[1];
        u32 totalFramesData[1];
        u32 individualNumData[1];
        u32 baseViewpointNumData[1];
        JpegMpEncoderIfdWorkObj indexIfdWork[NUM_APP2_MP_INDEX_IFDS];
        JpegMpEncoderIfdWorkObj attributeIfdWork[NUM_APP2_MP_ATTRIBUTE_IFDS];
        JpegTagWorkObj tagWork[NUM_JPEG_MP_ENCODER_APP2_TAGS];
    } app2;
    MpRegionsToBuildJpegData mpRegions;
};
}

}
}
}

#endif