#pragma once

#include "jpeg_MpTypesInternal.h"

#ifdef __cplusplus

namespace nn
{
namespace jpeg
{
namespace CTR
{

enum JpegMpDecoderApp1TagIndex
{

    JPEG_DECODER_APP1_TAG_INDEX_IFD0_ORIENTATION = 0,
    JPEG_DECODER_APP1_TAG_INDEX_IFD0_SOFTWARE,
    JPEG_DECODER_APP1_TAG_INDEX_IFD0_DATE_TIME,
    JPEG_DECODER_APP1_TAG_INDEX_IFD0_EXIF_IFD_POINTER,
    JPEG_DECODER_APP1_TAG_INDEX_IFD0_GPS_IFD_POINTER,

    JPEG_DECODER_APP1_TAG_INDEX_EXIF_MAKERNOTE,
    JPEG_DECODER_APP1_TAG_INDEX_EXIF_INTEROPERABILITY_IFD_POINTER,
    JPEG_DECODER_APP1_TAG_INDEX_EXIF_IMAGE_UNIQUE_ID,

    JPEG_DECODER_APP1_TAG_INDEX_MAKERNOTE_TWL_BEGIN,
    JPEG_DECODER_APP1_TAG_INDEX_MAKERNOTE_TWL_DUMMY1 = JPEG_DECODER_APP1_TAG_INDEX_MAKERNOTE_TWL_BEGIN - 1,
    JPEG_DECODER_APP1_TAG_INDEX_MAKERNOTE_TWL_PRIVATE,
    JPEG_DECODER_APP1_TAG_INDEX_MAKERNOTE_TWL_PHOTO,
    JPEG_DECODER_APP1_TAG_INDEX_MAKERNOTE_TWL_USER,

    JPEG_DECODER_APP1_TAG_INDEX_MAKERNOTE_CTR,
    JPEG_DECODER_APP1_TAG_INDEX_MAKERNOTE_TWL_END = JPEG_DECODER_APP1_TAG_INDEX_MAKERNOTE_CTR + detail::NUM_MAKER_NOTES,
    JPEG_DECODER_APP1_TAG_INDEX_MAKERNOTE_TWL_DUMMY2 = JPEG_DECODER_APP1_TAG_INDEX_MAKERNOTE_TWL_END - 1,

    JPEG_DECODER_APP1_TAG_INDEX_THUMB_JPEG_INTERCHANGE_FORMAT,
    JPEG_DECODER_APP1_TAG_INDEX_THUMB_JPEG_INTERCHANGE_FORMAT_LENGTH,

    JPEG_DECODER_APP1_TAG_INDEX_GPS_VERSION_ID,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_LATITUDE_REF,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_LATITUDE,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_LONGITUDE_REF,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_LONGITUDE,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_ALTITUDE_REF,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_ALTITUDE,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_TIME_STAMP,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_SATELLITES,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_STATUS,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_MEASURE_MODE,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_DOP,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_SPEED_REF,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_SPEED,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_TRACK_REF,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_TRACK,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_IMG_DIRECTION_REF,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_IMG_DIRECTION,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_MAP_DATUM,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_DEST_LATITUDE_REF,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_DEST_LATITUDE,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_DEST_LONGITUDE_REF,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_DEST_LONGITUDE,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_DEST_BEARING_REF,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_DEST_BEARING,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_DEST_DISTANCE_REF,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_DEST_DISTANCE,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_PROCESSING_METHOD,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_AREA_INFORMATION,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_DATE_STAMP,
    JPEG_DECODER_APP1_TAG_INDEX_GPS_DIFFERENTIAL,

    NUM_JPEG_DECODER_APP1_TAGS
};

enum JpegMpDecoderApp2MpIndexIfdTagIndex
{

    JPEG_DECODER_APP2_MP_INDEX_IFD_TAG_INDEX_MPF_VERSION = 0,
    JPEG_DECODER_APP2_MP_INDEX_IFD_TAG_INDEX_NUMBER_OF_IMAGES,
    JPEG_DECODER_APP2_MP_INDEX_IFD_TAG_INDEX_MP_ENTRY,
    JPEG_DECODER_APP2_MP_INDEX_IFD_TAG_INDEX_IMAGE_UID_LIST,
    JPEG_DECODER_APP2_MP_INDEX_IFD_TAG_INDEX_TOTAL_FRAMES,

    NUM_JPEG_DECODER_APP2_MP_INDEX_IFD_TAGS
};

enum JpegMpDecoderApp2MpAttributeTagIndex
{
    JPEG_DECODER_APP2_MP_ATTRIBUTE_TAG_INDEX_MPF_VERSION = 0,
    JPEG_DECODER_APP2_MP_ATTRIBUTE_TAG_INDEX_MP_INDIVIDUAL_NUM,
    JPEG_DECODER_APP2_MP_ATTRIBUTE_TAG_INDEX_PAN_ORIENTATION,
    JPEG_DECODER_APP2_MP_ATTRIBUTE_TAG_INDEX_PAN_OVERLAP_H,
    JPEG_DECODER_APP2_MP_ATTRIBUTE_TAG_INDEX_PAN_OVERLAP_V,
    JPEG_DECODER_APP2_MP_ATTRIBUTE_TAG_INDEX_BASE_VIEWPOINT_NUM,
    JPEG_DECODER_APP2_MP_ATTRIBUTE_TAG_INDEX_CONVERGENCE_ANGLE,
    JPEG_DECODER_APP2_MP_ATTRIBUTE_TAG_INDEX_BASELINE_LENGTH,
    JPEG_DECODER_APP2_MP_ATTRIBUTE_TAG_INDEX_VERTICAL_DIVERGENCE,
    JPEG_DECODER_APP2_MP_ATTRIBUTE_TAG_INDEX_AXIS_DISTANCE_X,
    JPEG_DECODER_APP2_MP_ATTRIBUTE_TAG_INDEX_AXIS_DISTANCE_Y,
    JPEG_DECODER_APP2_MP_ATTRIBUTE_TAG_INDEX_AXIS_DISTANCE_Z,
    JPEG_DECODER_APP2_MP_ATTRIBUTE_TAG_INDEX_YAW_ANGLE,
    JPEG_DECODER_APP2_MP_ATTRIBUTE_TAG_INDEX_PITCH_ANGLE,
    JPEG_DECODER_APP2_MP_ATTRIBUTE_TAG_INDEX_ROLL_ANGLE,

    NUM_JPEG_DECODER_APP2_MP_ATTRIBUTE_TAGS
};

struct JpegMpDecoderExifTagITN
{
    u8 index;
    u8 type;
    u16 tag;
};

const u32 JPEG_DECODER_XBLOCK_MAX = 2;
const u32 JPEG_DECODER_YBLOCK_MAX = 2;
const u32 JPEG_DECODER_DQT_MAX = 3;

const u32 JPEG_DECODER_JW_SIZE = 0x1800;

enum
{
    JPEG_DECODER_MARKER_BIT_SOF = 0x00000001,
    JPEG_DECODER_MARKER_BIT_HT0DC = 0x00000010,
    JPEG_DECODER_MARKER_BIT_HT1DC = 0x00000020,
    JPEG_DECODER_MARKER_BIT_HT0AC = 0x00000040,
    JPEG_DECODER_MARKER_BIT_HT1AC = 0x00000080,
    JPEG_DECODER_MARKER_BIT_DQT = 0x00001000,
    JPEG_DECODER_MARKER_BIT_SOS = 0x00010000,

    JPEG_DECODER_MARKER_MASK_HT_ALL = (JPEG_DECODER_MARKER_BIT_HT0DC | JPEG_DECODER_MARKER_BIT_HT1DC |
                                       JPEG_DECODER_MARKER_BIT_HT0AC | JPEG_DECODER_MARKER_BIT_HT1AC)
};

struct JpegMpDecoderContext;

typedef void (*JpegMpDecoderWriteFunc)(JpegMpDecoderContext* pCtx, s32 x, s32 y);

struct JpegMpDecoderContext
{
    const u8* pSrc;
    size_t srcSize;
    size_t dstSize;
    u32 RSTn_work;
    u32 RSTn_intr;
    void* pDst;
    u16 width;
    u16 height;
    u16 maxWidth;
    u16 maxHeight;

    u16 matchWidth;
    u16 matchHeight;

    s16 mtx00;
    s16 mtx30;
    s16 mtx40;
    s8 bitlen;
    u8 chitFF;

    u8 xblock;
    u8 yblock;
    u8 xstep;
    u8 ystep;

    u8 xyblocks;
    bool decodeApp2MpAttribute;
    bool app2MpIndexFound;
    bool app2MpAttributeFound;

    const u8* pApp2Mp;

    u32 outputBufferWidth;
    u32 outputBufferHeight;
    JpegMpDecoderWriteFunc pWriteFunc;

    union
    {

        struct
        {

            s8 errorCode;
            volatile bool isStopped;
        } s;
        vu32 isErrorOccurredOrStopped;
    } u;

    PixelFormat dstPixelFormat;
    bool isApp1LittleEndian;
    bool app1ExifFound;
    bool skipDecode;

    bool decodeThumbnail;
    u8 shrinkLevel;
    u8 qtIndex1;
    u8 qtIndex2;

    u32 bcode2;
    u32 srcOffset;
    const u8* pSrcLimit;

    u32 processedMarkers;
    u32 neededMarkers;
    u32 option;

    const u8* pApp1ExifOffsetBase;

    struct
    {
        const u8* pSrc2;
        u32 bcode3;
        u32 outputBufferWidthX2;
        u32 outputBufferWidthX3;
        u32 outputBufferWidthX4;
    } asmWork;

    union
    {
        s16 qy[64 * JPEG_DECODER_DQT_MAX];
        u32 force_qy_alignment;
    } qyUnion;

    union
    {

        s16 mtx[3][64];
        u32 force_mtx_alignment;
    } mtxUnion;

    u8 dcr[64];
    u8 dcb[64];

    union
    {
        u8 draw_block[64 * JPEG_DECODER_XBLOCK_MAX * JPEG_DECODER_YBLOCK_MAX];
        u32 force_draw_block_alignment;
    } drawBlockUnion;

    union
    {

        u8 jw[JPEG_DECODER_JW_SIZE];
        u32 force_jw_alignment;
    } jwUnion;

    u16 huffcode[257];
    s8 huffsize[257];
    u8 reserved2[1];

    JpegTagWorkObj app1TagWork[NUM_JPEG_DECODER_APP1_TAGS];

    union
    {
        JpegTagWorkObj indexIfd[NUM_JPEG_DECODER_APP2_MP_INDEX_IFD_TAGS];
        JpegTagWorkObj attribute[NUM_JPEG_DECODER_APP2_MP_ATTRIBUTE_TAGS];
    } app2MpTagWorkUnion;

    union
    {
        MpIndex index;
        MpAttribute attr;
    } app2MpForAppUnion;
};

namespace detail
{

struct JpegMpDecoderWorkObj
{

    JpegMpDecoderContext ctx;
};
}

}
}
}

#endif

