#pragma once

#define JPEG_ENCODER_USE_DHT_CACHE

#define JPEG_ENCODER_USE_DQT_CACHE

#include <nn/types.h>

#if NN_ENDIAN == NN_ENDIAN_VALUE_LITTLE
#define JPEG_ENCODER_EXIF_ENDIAN_IS
#else
#define JPEG_ENCODER_EXIF_ENDIAN_IS !
#endif

#include <nn/jpeg/CTR/jpeg_MpTypes.h>

#ifdef __cplusplus

namespace nn {
namespace jpeg {
namespace CTR {

enum App1TagNumber
{
    APP1_TAG_NUMBER_IFD0_MAKE = 0x010F,
    APP1_TAG_NUMBER_IFD0_MODEL = 0x0110,
    APP1_TAG_NUMBER_IFD0_ORIENTATION = 0x0112,
    APP1_TAG_NUMBER_IFD0_X_RESOLUTION = 0x011A,
    APP1_TAG_NUMBER_IFD0_Y_RESOLUTION = 0x011B,
    APP1_TAG_NUMBER_IFD0_RESOLUTION_UNIT = 0x0128,
    APP1_TAG_NUMBER_IFD0_SOFTWARE = 0x0131,
    APP1_TAG_NUMBER_IFD0_DATE_TIME = 0x0132,
    APP1_TAG_NUMBER_IFD0_YCBCR_POSITIONING = 0x0213,
    APP1_TAG_NUMBER_IFD0_EXIF_IFD_POINTER = 0x8769,
    APP1_TAG_NUMBER_IFD0_GPS_IFD_POINTER = 0x8825,

    APP1_TAG_NUMBER_EXIF_VERSION = 0x9000,
    APP1_TAG_NUMBER_EXIF_DATE_TIME_ORIGINAL = 0x9003,
    APP1_TAG_NUMBER_EXIF_DATE_TIME_DIGITIZED = 0x9004,
    APP1_TAG_NUMBER_EXIF_COMPONENTS_CONFIGURATION = 0x9101,
    APP1_TAG_NUMBER_EXIF_MAKERNOTE = 0x927C,
    APP1_TAG_NUMBER_EXIF_FLASHPIX_VERSION = 0xA000,
    APP1_TAG_NUMBER_EXIF_COLOR_SPACE = 0xA001,
    APP1_TAG_NUMBER_EXIF_PIXEL_X_DIMENSION = 0xA002,
    APP1_TAG_NUMBER_EXIF_PIXEL_Y_DIMENSION = 0xA003,
    APP1_TAG_NUMBER_EXIF_INTEROPERABILITY_IFD_POINTER = 0xA005,
    APP1_TAG_NUMBER_EXIF_IMAGE_UNIQUE_ID = 0xA420,

    APP1_TAG_NUMBER_INTEROPERABILITY_INDEX = 0x0001,
    APP1_TAG_NUMBER_INTEROPERABILITY_VERSION = 0x0002,
    APP1_TAG_NUMBER_INTEROPERABILITY_RELATED_IMAGE_FILE_FORMAT = 0x1000,

    APP1_TAG_NUMBER_THUMB_COMPRESSION = 0x0103,
    APP1_TAG_NUMBER_THUMB_X_RESOLUTION = APP1_TAG_NUMBER_IFD0_X_RESOLUTION,
    APP1_TAG_NUMBER_THUMB_Y_RESOLUTION = APP1_TAG_NUMBER_IFD0_Y_RESOLUTION,
    APP1_TAG_NUMBER_THUMB_RESOLUTION_UNIT = APP1_TAG_NUMBER_IFD0_RESOLUTION_UNIT,
    APP1_TAG_NUMBER_THUMB_JPEG_INTERCHANGE_FORMAT = 0x0201,
    APP1_TAG_NUMBER_THUMB_JPEG_INTERCHANGE_FORMAT_LENGTH = 0x0202
};

enum App1MakerNotePrivateTagNumber
{
    APP1_TAG_NUMBER_MAKERNOTE_TWL_PRIVATE = 0x1000,
    APP1_TAG_NUMBER_MAKERNOTE_TWL_PHOTO = 0x1001,
    APP1_TAG_NUMBER_MAKERNOTE_TWL_USER = 0x1002,

    APP1_TAG_NUMBER_MAKERNOTE_CTR = 0x1100
};

enum App1GpsTagNumber
{
    APP1_TAG_NUMBER_GPS_VERSION_ID = 0x0000,
    APP1_TAG_NUMBER_GPS_LATITUDE_REF = 0x0001,
    APP1_TAG_NUMBER_GPS_LATITUDE = 0x0002,
    APP1_TAG_NUMBER_GPS_LONGITUDE_REF = 0x0003,
    APP1_TAG_NUMBER_GPS_LONGITUDE = 0x0004,
    APP1_TAG_NUMBER_GPS_ALTITUDE_REF = 0x0005,
    APP1_TAG_NUMBER_GPS_ALTITUDE = 0x0006,
    APP1_TAG_NUMBER_GPS_TIME_STAMP = 0x0007,
    APP1_TAG_NUMBER_GPS_SATELLITES = 0x0008,
    APP1_TAG_NUMBER_GPS_STATUS = 0x0009,
    APP1_TAG_NUMBER_GPS_MEASURE_MODE = 0x000A,
    APP1_TAG_NUMBER_GPS_DOP = 0x000B,
    APP1_TAG_NUMBER_GPS_SPEED_REF = 0x000C,
    APP1_TAG_NUMBER_GPS_SPEED = 0x000D,
    APP1_TAG_NUMBER_GPS_TRACK_REF = 0x000E,
    APP1_TAG_NUMBER_GPS_TRACK = 0x000F,
    APP1_TAG_NUMBER_GPS_IMG_DIRECTION_REF = 0x0010,
    APP1_TAG_NUMBER_GPS_IMG_DIRECTION = 0x0011,
    APP1_TAG_NUMBER_GPS_MAP_DATUM = 0x0012,
    APP1_TAG_NUMBER_GPS_DEST_LATITUDE_REF = 0x0013,
    APP1_TAG_NUMBER_GPS_DEST_LATITUDE = 0x0014,
    APP1_TAG_NUMBER_GPS_DEST_LONGITUDE_REF = 0x0015,
    APP1_TAG_NUMBER_GPS_DEST_LONGITUDE = 0x0016,
    APP1_TAG_NUMBER_GPS_DEST_BEARING_REF = 0x0017,
    APP1_TAG_NUMBER_GPS_DEST_BEARING = 0x0018,
    APP1_TAG_NUMBER_GPS_DEST_DISTANCE_REF = 0x0019,
    APP1_TAG_NUMBER_GPS_DEST_DISTANCE = 0x001A,
    APP1_TAG_NUMBER_GPS_PROCESSING_METHOD = 0x001B,
    APP1_TAG_NUMBER_GPS_AREA_INFORMATION = 0x001C,
    APP1_TAG_NUMBER_GPS_DATE_STAMP = 0x001D,
    APP1_TAG_NUMBER_GPS_DIFFERENTIAL = 0x001E
};

enum App2MpTagNumber
{
    APP2_MP_TAG_NUMBER_MPF_VERSION = 0xB000,
    APP2_MP_TAG_NUMBER_NUMBER_OF_IMAGES = 0xB001,
    APP2_MP_TAG_NUMBER_MP_ENTRY = 0xB002,
    APP2_MP_TAG_NUMBER_IMAGE_UID_LIST = 0xB003,
    APP2_MP_TAG_NUMBER_TOTAL_FRAMES = 0xB004,

    APP2_MP_TAG_NUMBER_MPF_VERSION_SPECIAL = APP2_MP_TAG_NUMBER_MPF_VERSION,
    APP2_MP_TAG_NUMBER_MP_INDIVIDUAL_NUM = 0xB101,
    APP2_MP_TAG_NUMBER_PAN_ORIENTATION = 0xB201,
    APP2_MP_TAG_NUMBER_PAN_OVERLAP_H = 0xB202,
    APP2_MP_TAG_NUMBER_PAN_OVERLAP_V = 0xB203,
    APP2_MP_TAG_NUMBER_BASE_VIEWPOINT_NUM = 0xB204,
    APP2_MP_TAG_NUMBER_CONVERGENCE_ANGLE = 0xB205,
    APP2_MP_TAG_NUMBER_BASELINE_LENGTH = 0xB206,
    APP2_MP_TAG_NUMBER_VERTICAL_DIVERGENCE = 0xB207,
    APP2_MP_TAG_NUMBER_AXIS_DISTANCE_X = 0xB208,
    APP2_MP_TAG_NUMBER_AXIS_DISTANCE_Y = 0xB209,
    APP2_MP_TAG_NUMBER_AXIS_DISTANCE_Z = 0xB20A,
    APP2_MP_TAG_NUMBER_YAW_ANGLE = 0xB20B,
    APP2_MP_TAG_NUMBER_PITCH_ANGLE = 0xB20C,
    APP2_MP_TAG_NUMBER_ROLL_ANGLE = 0xB20D
};

enum ExifTagType
{
    EXIF_TAG_TYPE_BYTE = 1,
    EXIF_TAG_TYPE_ASCII = 2,
    EXIF_TAG_TYPE_SHORT = 3,
    EXIF_TAG_TYPE_LONG = 4,
    EXIF_TAG_TYPE_RATIONAL = 5,
    EXIF_TAG_TYPE_UNDEFINED = 7,
    EXIF_TAG_TYPE_SLONG = 9,
    EXIF_TAG_TYPE_SRATIONAL = 10,
    NUM_EXIF_TAG_TYPES
};

const size_t TIFF_FIELD_ENTRY_SIZE = 12;
const size_t TIFF_COUNT_SIZE = 2;
const size_t TIFF_OFFSET_SIZE = 4;
const size_t TIFF_COUNT_AND_OFFSET_SIZE = TIFF_COUNT_SIZE + TIFF_OFFSET_SIZE;

const size_t TIFF_RATIONAL_DATA_SIZE = 8;
const u32 TIFF_RATIONAL_UNKNOWN_DATA_VALUE = 0xFFFFFFFF;
const size_t TIFF_SRATIONAL_DATA_SIZE = 8;
const s32 TIFF_SRATIONAL_UNKNOWN_DATA_VALUE = static_cast<s32>(0xFFFFFFFF);

const size_t APP1_LENGTH_OFFSET = 4;
const size_t APP1_TIFF_OFFSET = 12;
const size_t APP1_TIFF_HEADER_SIZE = 8;

struct JpegTagWorkObj
{

    size_t dataSize;
    const u8* pData;
    u16 tag;
    u8 type;
    union
    {
        bool isMakerNoteSpecial;
        bool isFound;
    } u;
};

const size_t APP2_LENGTH_OFFSET = 2;
const size_t APP2_LENGTH_SIZE = 2;

const size_t APP2_MP_TIFF_OFFSET = 8;

const size_t APP2_MP_TIFF_HEADER_SIZE = 12;

}
}
}

#endif
