// Filename: os_PrintResultImpl.cpp
//
// Project: Horizon

#include <nn/Result.h>
#include <nn/os/os_Result.h>

#define BEGIN_GET_RESULT_DESCRIPTION_STRING_IMPL \
    const char* GetResultDescriptionStringImpl(nn::Result result) \
    { \
        (void)result; \
        if (0) {}

#define CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(nameSpace, description) \
        else if (result.GetDescription() == nameSpace::description) return #description;

#define END_GET_RESULT_DESCRIPTION_STRING_IMPL \
        return 0; \
    }

namespace nn {
namespace os {
namespace detail {

BEGIN_GET_RESULT_DESCRIPTION_STRING_IMPL
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_FAILED_TO_ALLOCATE_MEMORY)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_FAILED_TO_ALLOCATE_SHARED_MEMORY)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_FAILED_TO_ALLOCATE_THREAD)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_FAILED_TO_ALLOCATE_MUTEX)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_FAILED_TO_ALLOCATE_SEMAPHORE)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_FAILED_TO_ALLOCATE_EVENT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_FAILED_TO_ALLOCATE_TIMER)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_FAILED_TO_ALLOCATE_PORT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_FAILED_TO_ALLOCATE_SESSION)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_EXCEED_MEMORY_LIMIT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_EXCEED_SHARED_MEMORY_LIMIT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_EXCEED_THREAD_LIMIT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_EXCEED_MUTEX_LIMIT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_EXCEED_SEMAPHORE_LIMIT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_EXCEED_EVENT_LIMIT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_EXCEED_TIMER_LIMIT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_EXCEED_PORT_LIMIT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_EXCEED_SESSION_LIMIT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_MAX_HANDLE)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_INACCESSIBLE_PAGE)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_ABANDONED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_INVALID_PROCESS_ID)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_INVALID_THREAD_ID)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_SESSION_CLOSED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_INVALID_MESSAGE)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_MANUAL_RESET_EVENT_REQUIRED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_TOO_LONG_NAME)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_NOT_OWNED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_PROCESS_TERMINATED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_INVALID_TLS_INDEX)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_NO_RUNNABLE_PROCESSOR)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_NO_SESSION)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_USING_REGION)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_ALREADY_RECEIVED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_CANCEL_REQUESTD)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_NOT_RECEIVED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_DELIVER_ARG_NOT_READY)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_DELIVER_ARG_OVER_SIZE)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_INVALID_DELIVER_ARG)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_I_AM_OWNER)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_EXCEEDS_SHARED_LIMIT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_UNEXPECTED_PERMISSION)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_INVALID_TAG)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_INVALID_FORMAT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_OTHER_HANDLE)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_FAILED_TO_ALLOCATE_ADDRESS_ARBITER)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_EXCEED_ADDRESS_ARBITER_LIMIT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_OVER_PORT_CAPACITY)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_NOT_MAPPED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_BUFFER_TOO_FLAGMENTED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_NO_ADDRESS_SPACE)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_EXCEED_TLS_LIMIT)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_CANT_START)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_LOCKED)
    CASE_GET_RESULT_DESCRIPTION_STRING_IMPL(::nn::os, DESCRIPTION_OBSOLETE_RESULT)
END_GET_RESULT_DESCRIPTION_STRING_IMPL

void GetResultDescriptionStringImplKeeper()
{
    const char* (*volatile f)(nn::Result) = GetResultDescriptionStringImpl;
}

} // namespace detail
} // namespace os
} // namespace nn
