#pragma once

#define VER_STR_(version) #version
#define VER_STR(version) VER_STR_(version)

#define NN_VERSION_NONE        0
#define NN_VERSION_MILLI4C     1
#define NN_VERSION_REDPEPPER   2
#define NN_VERSION_CTRDASH     3 /* Is not defined. Multi-Game versions. */
#define NN_VERSION_GARDEN      4
#define NN_VERSION_STICKSTR    5

/* Your version here! */

#define NN_VERSION NN_VERSION_REDPEPPER

#if NN_VERSION == NN_VERSION_MILLI4C

#define NN_VERSION_MAJOR 4
#define NN_VERSION_MINOR 2
#define NN_VERSION_MICRO 5
#define NN_VERSION_ID    200

#define NN_VERSION_FIRMWARE_MAJOR 02
#define NN_VERSION_FIRMWARE_MINOR 35
#define NN_VERSION_FIRMWARE_MICRO 00

#define NN_VERSION_PATCH "none"

#elif NN_VERSION == NN_VERSION_REDPEPPER

#define NN_VERSION_MAJOR 2
#define NN_VERSION_MINOR 4
#define NN_VERSION_MICRO 1
#define NN_VERSION_ID    200

#define NN_VERSION_FIRMWARE_MAJOR 02
#define NN_VERSION_FIRMWARE_MINOR 30
#define NN_VERSION_FIRMWARE_MICRO 20

#define NN_VERSION_PATCH "none"

#elif NN_VERSION == NN_VERSION_STICKSTR

#define NN_VERSION_MAJOR 4
#define NN_VERSION_MINOR 2
#define NN_VERSION_MICRO 0
#define NN_VERSION_ID    200

#define NN_VERSION_FIRMWARE_MAJOR 02
#define NN_VERSION_FIRMWARE_MINOR 35
#define NN_VERSION_FIRMWARE_MICRO 00

#define NN_VERSION_PATCH "none"

/* Do this yourself */

#elif NN_VERSION == NN_VERSION_NONE

#define NN_VERSION_MAJOR 0
#define NN_VERSION_MINOR 0
#define NN_VERSION_MICRO 0
#define NN_VERSION_ID    0

#define NN_VERSION_FIRMWARE_MAJOR 00
#define NN_VERSION_FIRMWARE_MINOR 00
#define NN_VERSION_FIRMWARE_MICRO 00

#define NN_VERSION_PATCH "none"

#else

#define NN_VERSION_MAJOR
#define NN_VERSION_MINOR
#define NN_VERSION_MICRO
#define NN_VERSION_ID

#define NN_VERSION_FIRMWARE_MAJOR
#define NN_VERSION_FIRMWARE_MINOR
#define NN_VERSION_FIRMWARE_MICRO

#define NN_VERSION_PATCH "none"

#endif

#define NN_VERSION_RVCT_MAJOR 4
#define NN_VERSION_RVCT_MINOR 1
#define NN_VERSION_RVCT_REV   791

#ifndef NN_CURRENT_SDK_VERSION
#define NN_CURRENT_SDK_VERSION "CTR_SDK-"VER_STR(NN_VERSION_MAJOR)"_"VER_STR(NN_VERSION_MINOR)"_"VER_STR(NN_VERSION_MICRO)"_"VER_STR(NN_VERSION_ID)"_"NN_VERSION_PATCH
#endif

#ifndef NN_CURRENT_FIRMWARE_VERSION
#define NN_CURRENT_FIRMWARE_VERSION "Firmware-"VER_STR(NN_VERSION_FIRMWARE_MAJOR)"_"VER_STR(NN_VERSION_FIRMWARE_MINOR)"_"VER_STR(NN_VERSION_FIRMWARE_MICRO)
#endif

#ifndef NN_VERSION_NUMBER
#define NN_VERSION_NUMBER(major, minor, micro, id) (((major) << 24) | ((minor) << 16)  | ((micro) << 8) | (id << 0))

#define NN_CURRENT_VERSION_NUMBER NN_VERSION_NUMBER(NN_VERSION_MAJOR, NN_VERSION_MINOR, NN_VERSION_MICRO, NN_VERSION_ID)
#endif

#ifndef NN_FIRMWARE_NUMBER
#define NN_FIRMWARE_NUMBER(major, minor, micro) (((major) << 24) | ((minor) << 16)  | ((micro) << 8))

#define NN_CURRENT_FIRMWARE_NUMBER NN_VERSION_NUMBER(NN_VERSION_FIRMWARE_MAJOR, NN_VERSION_FIRMWARE_MINOR, NN_VERSION_FIRMWARE_MICRO)
#endif

