// Filename: dbg_PrintResult.cpp
//
// Project: Horizon

#include <nn/dbg/dbg_DebugString.h>

#include <nn/nstd/nstd_Printf.h>
#include <nn/module.h>
#include <nn/svc.h>

#include <string.h>
#include <cstdio>
#include <cstdarg>
#include <cstring>

#define PREDEFINE_GET_RESULT_DESCRIPTION(module)                           \
        namespace nn { namespace module { namespace detail{                                         \
            __weak const char* GetResultDescriptionStringImpl (Result) { return 0; }  \
        }}}

PREDEFINE_GET_RESULT_DESCRIPTION (kernel)
PREDEFINE_GET_RESULT_DESCRIPTION (util)
PREDEFINE_GET_RESULT_DESCRIPTION (file_server)
PREDEFINE_GET_RESULT_DESCRIPTION (loader_server)
PREDEFINE_GET_RESULT_DESCRIPTION (tcb)
PREDEFINE_GET_RESULT_DESCRIPTION (os)
PREDEFINE_GET_RESULT_DESCRIPTION (dbg)
PREDEFINE_GET_RESULT_DESCRIPTION (dmnt)
PREDEFINE_GET_RESULT_DESCRIPTION (pdn)
PREDEFINE_GET_RESULT_DESCRIPTION (gx)
PREDEFINE_GET_RESULT_DESCRIPTION (i2c)
PREDEFINE_GET_RESULT_DESCRIPTION (gpio)
PREDEFINE_GET_RESULT_DESCRIPTION (dd)
PREDEFINE_GET_RESULT_DESCRIPTION (codec)
PREDEFINE_GET_RESULT_DESCRIPTION (spi)
PREDEFINE_GET_RESULT_DESCRIPTION (pxi)
PREDEFINE_GET_RESULT_DESCRIPTION (fs)
PREDEFINE_GET_RESULT_DESCRIPTION (di)
PREDEFINE_GET_RESULT_DESCRIPTION (hid)
PREDEFINE_GET_RESULT_DESCRIPTION (camera)
PREDEFINE_GET_RESULT_DESCRIPTION (pi)
PREDEFINE_GET_RESULT_DESCRIPTION (pm)
PREDEFINE_GET_RESULT_DESCRIPTION (pmlow)
PREDEFINE_GET_RESULT_DESCRIPTION (fsi)
PREDEFINE_GET_RESULT_DESCRIPTION (srv)
PREDEFINE_GET_RESULT_DESCRIPTION (ndm)
PREDEFINE_GET_RESULT_DESCRIPTION (nwm)
PREDEFINE_GET_RESULT_DESCRIPTION (socket)
PREDEFINE_GET_RESULT_DESCRIPTION (ldr)
PREDEFINE_GET_RESULT_DESCRIPTION (acc)
PREDEFINE_GET_RESULT_DESCRIPTION (romfs)
PREDEFINE_GET_RESULT_DESCRIPTION (am)
PREDEFINE_GET_RESULT_DESCRIPTION (hio)
PREDEFINE_GET_RESULT_DESCRIPTION (updater)
PREDEFINE_GET_RESULT_DESCRIPTION (mic)
PREDEFINE_GET_RESULT_DESCRIPTION (fnd)
PREDEFINE_GET_RESULT_DESCRIPTION (mp)
PREDEFINE_GET_RESULT_DESCRIPTION (mpwl)
PREDEFINE_GET_RESULT_DESCRIPTION (ac)
PREDEFINE_GET_RESULT_DESCRIPTION (http)
PREDEFINE_GET_RESULT_DESCRIPTION (dsp)
PREDEFINE_GET_RESULT_DESCRIPTION (snd)
PREDEFINE_GET_RESULT_DESCRIPTION (dlp)
PREDEFINE_GET_RESULT_DESCRIPTION (hiolow)
PREDEFINE_GET_RESULT_DESCRIPTION (csnd)
PREDEFINE_GET_RESULT_DESCRIPTION (ssl)
PREDEFINE_GET_RESULT_DESCRIPTION (amlow)
PREDEFINE_GET_RESULT_DESCRIPTION (nex)
PREDEFINE_GET_RESULT_DESCRIPTION (friends)
PREDEFINE_GET_RESULT_DESCRIPTION (rdt)
PREDEFINE_GET_RESULT_DESCRIPTION (applet)
PREDEFINE_GET_RESULT_DESCRIPTION (nim)
PREDEFINE_GET_RESULT_DESCRIPTION (ptm)
PREDEFINE_GET_RESULT_DESCRIPTION (midi)
PREDEFINE_GET_RESULT_DESCRIPTION (mc)
PREDEFINE_GET_RESULT_DESCRIPTION (swc)
PREDEFINE_GET_RESULT_DESCRIPTION (fatfs)
PREDEFINE_GET_RESULT_DESCRIPTION (ngc)
PREDEFINE_GET_RESULT_DESCRIPTION (card)
PREDEFINE_GET_RESULT_DESCRIPTION (cardnor)
PREDEFINE_GET_RESULT_DESCRIPTION (sdmc)
PREDEFINE_GET_RESULT_DESCRIPTION (boss)
PREDEFINE_GET_RESULT_DESCRIPTION (dbm)
PREDEFINE_GET_RESULT_DESCRIPTION (cfg)
PREDEFINE_GET_RESULT_DESCRIPTION (ps)
PREDEFINE_GET_RESULT_DESCRIPTION (cec)
PREDEFINE_GET_RESULT_DESCRIPTION (ir)
PREDEFINE_GET_RESULT_DESCRIPTION (uds)
PREDEFINE_GET_RESULT_DESCRIPTION (pl)
PREDEFINE_GET_RESULT_DESCRIPTION (cup)
PREDEFINE_GET_RESULT_DESCRIPTION (gyroscope)
PREDEFINE_GET_RESULT_DESCRIPTION (mcu)
PREDEFINE_GET_RESULT_DESCRIPTION (ns)
PREDEFINE_GET_RESULT_DESCRIPTION (news)
PREDEFINE_GET_RESULT_DESCRIPTION (ro)
PREDEFINE_GET_RESULT_DESCRIPTION (gd)
PREDEFINE_GET_RESULT_DESCRIPTION (cardspi)
PREDEFINE_GET_RESULT_DESCRIPTION (ec)
PREDEFINE_GET_RESULT_DESCRIPTION (webbrs)
PREDEFINE_GET_RESULT_DESCRIPTION (test)
PREDEFINE_GET_RESULT_DESCRIPTION (enc)
PREDEFINE_GET_RESULT_DESCRIPTION (pia)

namespace nn{
namespace dbg{
namespace detail{

#define ENTRY_GET_RESULT_DESCRIPTION(Func, Desc) \
        if (result.Func () == Result::Desc)      \
        return #Desc

#define ENTRY_GET_RESULT_DESCRIPTION_FALLBACK \
        return "<unknown>"

#define ENTRY_GET_RESULT_DESCRIPTION_LVL(Desc) \
        ENTRY_GET_RESULT_DESCRIPTION (GetSummary, Desc)

const char* GetLevelString (Result result)
{
    ENTRY_GET_RESULT_DESCRIPTION_LVL (LEVEL_INFO);
    ENTRY_GET_RESULT_DESCRIPTION_LVL (LEVEL_SUCCESS);
    ENTRY_GET_RESULT_DESCRIPTION_LVL (LEVEL_FATAL);
    ENTRY_GET_RESULT_DESCRIPTION_LVL (LEVEL_RESET);
    ENTRY_GET_RESULT_DESCRIPTION_LVL (LEVEL_REINIT);
    ENTRY_GET_RESULT_DESCRIPTION_LVL (LEVEL_USAGE);
    ENTRY_GET_RESULT_DESCRIPTION_LVL (LEVEL_PERMANENT);
    ENTRY_GET_RESULT_DESCRIPTION_LVL (LEVEL_TEMPORARY);
    ENTRY_GET_RESULT_DESCRIPTION_LVL (LEVEL_STATUS);
    ENTRY_GET_RESULT_DESCRIPTION_FALLBACK;
}

#define ENTRY_GET_RESULT_DESCRIPTION_SUM(Desc) \
        ENTRY_GET_RESULT_DESCRIPTION (GetSummary, Desc)

const char* GetSummaryString (Result result)
{
    ENTRY_GET_RESULT_DESCRIPTION_SUM (SUMMARY_SUCCESS);
    ENTRY_GET_RESULT_DESCRIPTION_SUM (SUMMARY_NOTHING_HAPPENED);
    ENTRY_GET_RESULT_DESCRIPTION_SUM (SUMMARY_WOULD_BLOCK);
    ENTRY_GET_RESULT_DESCRIPTION_SUM (SUMMARY_OUT_OF_RESOURCE);
    ENTRY_GET_RESULT_DESCRIPTION_SUM (SUMMARY_NOT_FOUND);
    ENTRY_GET_RESULT_DESCRIPTION_SUM (SUMMARY_INVALID_STATE);
    ENTRY_GET_RESULT_DESCRIPTION_SUM (SUMMARY_NOT_SUPPORTED);
    ENTRY_GET_RESULT_DESCRIPTION_SUM (SUMMARY_INVALID_ARGUMENT);
    ENTRY_GET_RESULT_DESCRIPTION_SUM (SUMMARY_WRONG_ARGUMENT);
    ENTRY_GET_RESULT_DESCRIPTION_SUM (SUMMARY_CANCELLED);
    ENTRY_GET_RESULT_DESCRIPTION_SUM (SUMMARY_STATUS_CHANGED);
    ENTRY_GET_RESULT_DESCRIPTION_SUM (SUMMARY_INTERNAL);
    ENTRY_GET_RESULT_DESCRIPTION_FALLBACK;
}

#define ENTRY_GET_RESULT_DESCRIPTION_MOD(Desc) \
        ENTRY_GET_RESULT_DESCRIPTION (GetModule, Desc)

const char* GetModuleString (Result result)
{
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_COMMON);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_KERNEL);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_UTIL);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_FILE_SERVER);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_LOADER_SERVER);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_TCB);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_OS);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_DBG);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_DMNT);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_PDN);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_GX);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_I2C);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_GPIO);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_DD);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_CODEC);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_SPI);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_PXI);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_FS);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_DI);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_HID);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_CAMERA);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_PI);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_PM);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_PMLOW);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_FSI);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_SRV);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_NDM);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_NWM);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_SOCKET);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_LDR);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_ACC);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_ROMFS);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_AM);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_HIO);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_UPDATER);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_MIC);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_FND);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_MP);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_MPWL);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_AC);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_HTTP);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_DSP);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_SND);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_DLP);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_HIOLOW);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_CSND);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_SSL);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_AMLOW);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_NEX);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_FRIENDS);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_RDT);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_APPLET);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_NIM);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_PTM);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_MIDI);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_MC);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_SWC);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_FATFS);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_NGC);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_CARD);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_CARDNOR);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_SDMC);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_BOSS);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_DBM);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_CFG);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_PS);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_CEC);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_IR);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_UDS);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_PL);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_CUP);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_GYROSCOPE);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_MCU);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_NS);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_NEWS);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_RO);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_GD);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_CARDSPI);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_EC);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_WEBBRS);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_TEST);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_ENC);
    ENTRY_GET_RESULT_DESCRIPTION_MOD (MODULE_NN_PIA);
    ENTRY_GET_RESULT_DESCRIPTION_FALLBACK;
}

#define ENTRY_GET_RESULT_DESCRIPTION_DESC(Desc) \
        ENTRY_GET_RESULT_DESCRIPTION (GetDescription, Desc)

const char* GetResultCommonDescriptionStringImpl (Result result)
{
    ENTRY_GET_RESULT_DESCRIPTION_DESC (DESCRIPTION_SUCCESS);
    ENTRY_GET_RESULT_DESCRIPTION_DESC (DESCRIPTION_INVALID_SELECTION);
    ENTRY_GET_RESULT_DESCRIPTION_DESC (DESCRIPTION_TOO_LARGE);
    ENTRY_GET_RESULT_DESCRIPTION_DESC (DESCRIPTION_NOT_AUTHORIZED);
    ENTRY_GET_RESULT_DESCRIPTION_DESC (DESCRIPTION_ALREADY_DONE);
    ENTRY_GET_RESULT_DESCRIPTION_DESC (DESCRIPTION_INVALID_SIZE);
    ENTRY_GET_RESULT_DESCRIPTION_DESC (DESCRIPTION_INVALID_ENUM_VALUE);
    ENTRY_GET_RESULT_DESCRIPTION_DESC (DESCRIPTION_INVALID_COMBINATION);
    ENTRY_GET_RESULT_DESCRIPTION_DESC (DESCRIPTION_NO_DATA);
    ENTRY_GET_RESULT_DESCRIPTION_DESC (DESCRIPTION_BUSY);
    ENTRY_GET_RESULT_DESCRIPTION_DESC (DESCRIPTION_MISALIGNED_ADDRESS);
    ENTRY_GET_RESULT_DESCRIPTION_DESC (DESCRIPTION_MISALIGNED_SIZE);
    ENTRY_GET_RESULT_DESCRIPTION_DESC (DESCRIPTION_OUT_OF_MEMORY);
    ENTRY_GET_RESULT_DESCRIPTION_DESC (DESCRIPTION_NOT_IMPLEMENTED);
    ENTRY_GET_RESULT_DESCRIPTION_DESC (DESCRIPTION_INVALID_ADDRESS);
    ENTRY_GET_RESULT_DESCRIPTION_DESC (DESCRIPTION_INVALID_POINTER);
    ENTRY_GET_RESULT_DESCRIPTION_DESC (DESCRIPTION_INVALID_HANDLE);
    ENTRY_GET_RESULT_DESCRIPTION_DESC (DESCRIPTION_NOT_INITIALIZED);
    ENTRY_GET_RESULT_DESCRIPTION_DESC (DESCRIPTION_ALREADY_INITIALIZED);
    ENTRY_GET_RESULT_DESCRIPTION_DESC (DESCRIPTION_NOT_FOUND);
    ENTRY_GET_RESULT_DESCRIPTION_DESC (DESCRIPTION_CANCEL_REQUESTED);
    ENTRY_GET_RESULT_DESCRIPTION_DESC (DESCRIPTION_ALREADY_EXISTS);
    ENTRY_GET_RESULT_DESCRIPTION_DESC (DESCRIPTION_OUT_OF_RANGE);
    ENTRY_GET_RESULT_DESCRIPTION_DESC (DESCRIPTION_TIMEOUT);
    ENTRY_GET_RESULT_DESCRIPTION_DESC (DESCRIPTION_INVALID_RESULT_VALUE);
    ENTRY_GET_RESULT_DESCRIPTION_FALLBACK;
}
#define CALL_GET_RESULT_DESCRIPTION(module, e) \
        case Result::e: desc = ::nn::module::detail::GetResultDescriptionStringImpl (result); break;

const char* GetDescriptionString (Result result)
{
    const char* desc = NULL;
    switch (result.GetModule ()) {
        CALL_GET_RESULT_DESCRIPTION (kernel, MODULE_NN_KERNEL)
        CALL_GET_RESULT_DESCRIPTION (util, MODULE_NN_UTIL)
        CALL_GET_RESULT_DESCRIPTION (file_server, MODULE_NN_FILE_SERVER)
        CALL_GET_RESULT_DESCRIPTION (loader_server, MODULE_NN_LOADER_SERVER)
        CALL_GET_RESULT_DESCRIPTION (tcb, MODULE_NN_TCB)
        CALL_GET_RESULT_DESCRIPTION (os, MODULE_NN_OS)
        CALL_GET_RESULT_DESCRIPTION (dbg, MODULE_NN_DBG)
        CALL_GET_RESULT_DESCRIPTION (dmnt, MODULE_NN_DMNT)
        CALL_GET_RESULT_DESCRIPTION (pdn, MODULE_NN_PDN)
        CALL_GET_RESULT_DESCRIPTION (gx, MODULE_NN_GX)
        CALL_GET_RESULT_DESCRIPTION (i2c, MODULE_NN_I2C)
        CALL_GET_RESULT_DESCRIPTION (gpio, MODULE_NN_GPIO)
        CALL_GET_RESULT_DESCRIPTION (dd, MODULE_NN_DD)
        CALL_GET_RESULT_DESCRIPTION (codec, MODULE_NN_CODEC)
        CALL_GET_RESULT_DESCRIPTION (spi, MODULE_NN_SPI)
        CALL_GET_RESULT_DESCRIPTION (pxi, MODULE_NN_PXI)
        CALL_GET_RESULT_DESCRIPTION (fs, MODULE_NN_FS)
        CALL_GET_RESULT_DESCRIPTION (di, MODULE_NN_DI)
        CALL_GET_RESULT_DESCRIPTION (hid, MODULE_NN_HID)
        CALL_GET_RESULT_DESCRIPTION (camera, MODULE_NN_CAMERA)
        CALL_GET_RESULT_DESCRIPTION (pi, MODULE_NN_PI)
        CALL_GET_RESULT_DESCRIPTION (pm, MODULE_NN_PM)
        CALL_GET_RESULT_DESCRIPTION (pmlow, MODULE_NN_PMLOW)
        CALL_GET_RESULT_DESCRIPTION (fsi, MODULE_NN_FSI)
        CALL_GET_RESULT_DESCRIPTION (srv, MODULE_NN_SRV)
        CALL_GET_RESULT_DESCRIPTION (ndm, MODULE_NN_NDM)
        CALL_GET_RESULT_DESCRIPTION (nwm, MODULE_NN_NWM)
        CALL_GET_RESULT_DESCRIPTION (socket, MODULE_NN_SOCKET)
        CALL_GET_RESULT_DESCRIPTION (ldr, MODULE_NN_LDR)
        CALL_GET_RESULT_DESCRIPTION (acc, MODULE_NN_ACC)
        CALL_GET_RESULT_DESCRIPTION (romfs, MODULE_NN_ROMFS)
        CALL_GET_RESULT_DESCRIPTION (am, MODULE_NN_AM)
        CALL_GET_RESULT_DESCRIPTION (hio, MODULE_NN_HIO)
        CALL_GET_RESULT_DESCRIPTION (updater, MODULE_NN_UPDATER)
        CALL_GET_RESULT_DESCRIPTION (mic, MODULE_NN_MIC)
        CALL_GET_RESULT_DESCRIPTION (fnd, MODULE_NN_FND)
        CALL_GET_RESULT_DESCRIPTION (mp, MODULE_NN_MP)
        CALL_GET_RESULT_DESCRIPTION (mpwl, MODULE_NN_MPWL)
        CALL_GET_RESULT_DESCRIPTION (ac, MODULE_NN_AC)
        CALL_GET_RESULT_DESCRIPTION (http, MODULE_NN_HTTP)
        CALL_GET_RESULT_DESCRIPTION (dsp, MODULE_NN_DSP)
        CALL_GET_RESULT_DESCRIPTION (snd, MODULE_NN_SND)
        CALL_GET_RESULT_DESCRIPTION (dlp, MODULE_NN_DLP)
        CALL_GET_RESULT_DESCRIPTION (hiolow, MODULE_NN_HIOLOW)
        CALL_GET_RESULT_DESCRIPTION (csnd, MODULE_NN_CSND)
        CALL_GET_RESULT_DESCRIPTION (ssl, MODULE_NN_SSL)
        CALL_GET_RESULT_DESCRIPTION (amlow, MODULE_NN_AMLOW)
        CALL_GET_RESULT_DESCRIPTION (nex, MODULE_NN_NEX)
        CALL_GET_RESULT_DESCRIPTION (friends, MODULE_NN_FRIENDS)
        CALL_GET_RESULT_DESCRIPTION (rdt, MODULE_NN_RDT)
        CALL_GET_RESULT_DESCRIPTION (applet, MODULE_NN_APPLET)
        CALL_GET_RESULT_DESCRIPTION (nim, MODULE_NN_NIM)
        CALL_GET_RESULT_DESCRIPTION (ptm, MODULE_NN_PTM)
        CALL_GET_RESULT_DESCRIPTION (midi, MODULE_NN_MIDI)
        CALL_GET_RESULT_DESCRIPTION (mc, MODULE_NN_MC)
        CALL_GET_RESULT_DESCRIPTION (swc, MODULE_NN_SWC)
        CALL_GET_RESULT_DESCRIPTION (fatfs, MODULE_NN_FATFS)
        CALL_GET_RESULT_DESCRIPTION (ngc, MODULE_NN_NGC)
        CALL_GET_RESULT_DESCRIPTION (card, MODULE_NN_CARD)
        CALL_GET_RESULT_DESCRIPTION (cardnor, MODULE_NN_CARDNOR)
        CALL_GET_RESULT_DESCRIPTION (sdmc, MODULE_NN_SDMC)
        CALL_GET_RESULT_DESCRIPTION (boss, MODULE_NN_BOSS)
        CALL_GET_RESULT_DESCRIPTION (dbm, MODULE_NN_DBM)
        CALL_GET_RESULT_DESCRIPTION (cfg, MODULE_NN_CFG)
        CALL_GET_RESULT_DESCRIPTION (ps, MODULE_NN_PS)
        CALL_GET_RESULT_DESCRIPTION (cec, MODULE_NN_CEC)
        CALL_GET_RESULT_DESCRIPTION (ir, MODULE_NN_IR)
        CALL_GET_RESULT_DESCRIPTION (uds, MODULE_NN_UDS)
        CALL_GET_RESULT_DESCRIPTION (pl, MODULE_NN_PL)
        CALL_GET_RESULT_DESCRIPTION (cup, MODULE_NN_CUP)
        CALL_GET_RESULT_DESCRIPTION (gyroscope, MODULE_NN_GYROSCOPE)
        CALL_GET_RESULT_DESCRIPTION (mcu, MODULE_NN_MCU)
        CALL_GET_RESULT_DESCRIPTION (ns, MODULE_NN_NS)
        CALL_GET_RESULT_DESCRIPTION (news, MODULE_NN_NEWS)
        CALL_GET_RESULT_DESCRIPTION (ro, MODULE_NN_RO)
        CALL_GET_RESULT_DESCRIPTION (gd, MODULE_NN_GD)
        CALL_GET_RESULT_DESCRIPTION (cardspi, MODULE_NN_CARDSPI)
        CALL_GET_RESULT_DESCRIPTION (ec, MODULE_NN_EC)
        CALL_GET_RESULT_DESCRIPTION (webbrs, MODULE_NN_WEBBRS)
        CALL_GET_RESULT_DESCRIPTION (test, MODULE_NN_TEST)
        CALL_GET_RESULT_DESCRIPTION (enc, MODULE_NN_ENC)
        CALL_GET_RESULT_DESCRIPTION (pia, MODULE_NN_PIA)
    default: break;
    }

    if (desc == NULL)
    {
        desc = nn::dbg::detail::GetResultCommonDescriptionStringImpl (result);
    }
    if (desc == NULL)
    {
        desc = "Unknown description";
    }

    return desc;
}

void PrintResult(Result result)
{
    NN_LOG_("Result (%08x)\n", result.GetPrintableBits());
    NN_LOG_("Level:       (%4d) %s\n",result.GetLevel(), GetLevelString(result));
    NN_LOG_("Summary:     (%4d) %s\n",result.GetSummary(), GetSummaryString(result));
    NN_LOG_("Module:      (%4d) %s\n",result.GetModule(), GetModuleString(result));
    NN_LOG_("Description: (%4d) %s\n",result.GetDescription(), GetDescriptionString(result));
}

void TPrintResult(Result result)
{
    NN_TLOG_("Result (%08x)\n", result.GetPrintableBits());
    NN_TLOG_("Level:       (%4d) %s\n",result.GetLevel(), GetLevelString(result));
    NN_TLOG_("Summary:     (%4d) %s\n",result.GetSummary(), GetSummaryString(result));
    NN_TLOG_("Module:      (%4d) %s\n",result.GetModule(), GetModuleString(result));
    NN_TLOG_("Description: (%4d) %s\n",result.GetDescription(), GetDescriptionString(result));
}

} // namespace detail
} // namespace dbg
} // namespace nn