#pragma once

typedef enum GARNET_PDC_REG_T{
	GARNET_REG_PDC_0_BASE = 0,
	GARNET_REG_PDC_H_COUNT_SIZE_0 = GARNET_REG_PDC_0_BASE,
	GARNET_REG_PDC_H_ADDR_TIME_START_0,
	GARNET_REG_PDC_H_RIGHT_BORDER_START_0,
	GARNET_REG_PDC_H_BLANK_START_0,
	GARNET_REG_PDC_H_SYNC_START_0,
	GARNET_REG_PDC_H_BACK_PORCH_START_0,
	GARNET_REG_PDC_H_LEFT_BORDER_START_0,
	GARNET_REG_PDC_H_INTERRUPT_TIMING_0,
	GARNET_REG_PDC_H_DMA_TIMING_0,
	GARNET_REG_PDC_V_COUNTER_SIZE_0,
	GARNET_REG_PDC_V_ADDR_TIME_START_0,
	GARNET_REG_PDC_V_BOTTOM_BORDER_START_0,
	GARNET_REG_PDC_V_BLANK_START_0,
	GARNET_REG_PDC_V_SYNC_START_0,
	GARNET_REG_PDC_V_BACK_PORCH_START_0,
	GARNET_REG_PDC_V_TOP_BORDER_START_0,
	GARNET_REG_PDC_V_INTERRUPT_TIMING_0,
	GARNET_REG_PDC_V_INCREMENT_H_VALUE_0,
	GARNET_REG_PDC_SIGNAL_POL_0,
	GARNET_REG_PDC_BORDER_COLOR_0,
	GARNET_REG_PDC_H_STATUS_0,
	GARNET_REG_PDC_V_STATUS_0,
	GARNET_REG_PDC_SRC_SIZE_0,
	GARNET_REG_PDC_OUT_SIZE_0,
	GARNET_REG_PDC_PIC_BORDER_H_0,
	GARNET_REG_PDC_PIC_BORDER_V_0,
	GARNET_REG_PDC_FB0_ADR_0,
	GARNET_REG_PDC_FB1_ADR_0,
	GARNET_REG_PDC_MODE_0,
	GARNET_REG_PDC_START_0,
	GARNET_REG_PDC_SWAP_0,
	GARNET_REG_PDC_STATUS_0,
	GARNET_REG_PDC_RAM_ADR_0,
	GARNET_REG_PDC_RAM_DATA_0,
	GARNET_REG_PDC_RESERVE_0088h,
	GARNET_REG_PDC_RESERVE_008ch,
	GARNET_REG_PDC_FB_SIZE_0,
	GARNET_REG_PDC_FB0_B_ADR_0,
	GARNET_REG_PDC_FB1_B_ADR_0,
	GARNET_REG_PDC_REG_UPDATE_0,
	GARNET_REG_PDC_1_BASE = 0x40,
	GARNET_REG_PDC_H_COUNT_SIZE_1 = GARNET_REG_PDC_1_BASE,
	GARNET_REG_PDC_H_ADDR_TIME_START_1,
	GARNET_REG_PDC_H_RIGHT_BORDER_START_1,
	GARNET_REG_PDC_H_BLANK_START_1,
	GARNET_REG_PDC_H_SYNC_START_1,
	GARNET_REG_PDC_H_BACK_PORCH_START_1,
	GARNET_REG_PDC_H_LEFT_BORDER_START_1,
	GARNET_REG_PDC_H_INTERRUPT_TIMING_1,
	GARNET_REG_PDC_H_DMA_TIMING_1,
	GARNET_REG_PDC_V_COUNTER_SIZE_1,
	GARNET_REG_PDC_V_ADDR_TIME_START_1,
	GARNET_REG_PDC_V_BOTTOM_BORDER_START_1,
	GARNET_REG_PDC_V_BLANK_START_1,
	GARNET_REG_PDC_V_SYNC_START_1,
	GARNET_REG_PDC_V_BACK_PORCH_START_1,
	GARNET_REG_PDC_V_TOP_BORDER_START_1,
	GARNET_REG_PDC_V_INTERRUPT_TIMING_1,
	GARNET_REG_PDC_V_INCREMENT_H_VALUE_1,
	GARNET_REG_PDC_SIGNAL_POL_1,
	GARNET_REG_PDC_BORDER_COLOR_1,
	GARNET_REG_PDC_H_STATUS_1,
	GARNET_REG_PDC_V_STATUS_1,
	GARNET_REG_PDC_SRC_SIZE_1,
	GARNET_REG_PDC_OUT_SIZE_1,
	GARNET_REG_PDC_PIC_BORDER_H_1,
	GARNET_REG_PDC_PIC_BORDER_V_1,
	GARNET_REG_PDC_FB0_ADR_1,
	GARNET_REG_PDC_FB1_ADR_1,
	GARNET_REG_PDC_MODE_1,
	GARNET_REG_PDC_START_1,
	GARNET_REG_PDC_SWAP_1,
	GARNET_REG_PDC_STATUS_1,
	GARNET_REG_PDC_RAM_ADR_1,
	GARNET_REG_PDC_RAM_DATA_1,
	GARNET_REG_PDC_RESERVE_0188h,
	GARNET_REG_PDC_RESERVE_018ch,
	GARNET_REG_PDC_FB_SIZE_1,
	GARNET_REG_PDC_FB0_B_ADR_1,
	GARNET_REG_PDC_FB1_B_ADR_1,
	GARNET_REG_PDC_REG_UPDATE_1,
	GARNET_REG_PDC_NUM,
	
	GARNET_REG_PDC_MAX_BIT = (1u << 30)
} garnet_pdc_reg_t;

typedef enum GARNET_PPF_REG_T{
	GARNET_REG_PPF_SRC_ADR = 0,
	GARNET_REG_PPF_DST_ADR,
	GARNET_REG_PPF_SIZE,
	GARNET_REG_PPF_VSIZE,
	GARNET_REG_PPF_MODE,
	GARNET_REG_PPF_INTERVAL,
	GARNET_REG_PPF_START,
	GARNET_REG_PPF_WORK_LINE,
	GARNET_REG_PPF_DMA_SIZE,
	GARNET_REG_PPF_DMA_SRC_INTERVAL,
	GARNET_REG_PPF_DMA_DST_INTERVAL,
	GARNET_REG_PPF_NUM,
	
	GARNET_REG_PPF_MAX_BIT = (1u << 30)
} garnet_ppf_reg_t;

typedef struct GARNET_PPF_REG_MODE_T{
	unsigned		yflip		: 1;
	unsigned		l2b			: 1;
	unsigned		crop		: 1;
	unsigned		dmac		: 1;
	unsigned		rsv00		: 1;
	unsigned		b2b			: 1;
	unsigned		rsv01		: 2;
	unsigned		sformat		: 3;
	unsigned		rsv1		: 1;
	unsigned		dformat		: 3;
	unsigned		rsv2		: 1;
	unsigned		blk32		: 1;
	unsigned		rsv3		: 7;
	unsigned		amode		: 2;
	unsigned		rsv4		: 6;
} garnet_ppf_reg_mode_t;

typedef enum GARNET_PPF_FORMAT_T{
	GARNET_PPF_FORMAT_R8G8B8A8 = 0,
	GARNET_PPF_FORMAT_R8G8B8,
	GARNET_PPF_FORMAT_R5G6B5,
	GARNET_PPF_FORMAT_R5G5B5A1,
	GARNET_PPF_FORMAT_R4G4B4A4,
	
	GARNET_PPF_FORMAT_MAX_BIT = (1u << 30)
} garnet_ppf_format_t;

typedef enum GARNET_PPF_AMODE_T{
	GARNET_PPF_AMODE_NOP = 0,
	GARNET_PPF_AMODE_2x1,
	GARNET_PPF_AMODE_2x2,
	
	GARNET_PPF_AMODE_MAX_BIT = (1u << 30)
} garnet_ppf_amode_t;

typedef enum GARNET_PSC_FILL_FORMAT_T{
	GARNET_PSC_FILL_FORMAT_16 = 0,
	GARNET_PSC_FILL_FORMAT_24,
	GARNET_PSC_FILL_FORMAT_32,
	GARNET_PSC_FILL_FORMAT_RSV,
	
	GARNET_PSC_FILL_MAX_BIT = (1u << 30)
} garnet_psc_fill_format_t;

typedef enum GARNET_PSC_REG_T{
	GARNET_REG_PSC_ID = 0,
	GARNET_REG_PSC_CLK_MODE,
	GARNET_REG_PSC_RSV0,
	GARNET_REG_PSC_RSV1,
	GARNET_REG_PSC_FILL_START_ADR_0,
	GARNET_REG_PSC_FILL_END_ADR_0,
	GARNET_REG_PSC_FILL_DATA_0,
	GARNET_REG_PSC_FILL_CTRL_0,
	GARNET_REG_PSC_FILL_START_ADR_1,
	GARNET_REG_PSC_FILL_END_ADR_1,
	GARNET_REG_PSC_FILL_DATA_1,
	GARNET_REG_PSC_FILL_CTRL_1,
	GARNET_REG_PSC_SRAM_MODE,
	GARNET_REG_PSC_PHI_B_ERR_CODE,
	GARNET_REG_PSC_PHI_B_ERR_ADR,
	GARNET_REG_PSC_PHI_B_ERR_CLR,
	GARNET_REG_PSC_PHI_C_ERR_CODE,
	GARNET_REG_PSC_PHI_C_ERR_ADR,
	GARNET_REG_PSC_PHI_C_ERR_CLR,
	GARNET_REG_PSC_RSV2,
	GARNET_REG_PSC_PMI_PRIORITY_4P,
	GARNET_REG_PSC_PMI_PRIORITY_FCRAM_S01_3P,
	GARNET_REG_PSC_DEBUG,
	GARNET_REG_PSC_INTLOG_CTRL,
	GARNET_REG_PSC_INTLOG_READ,
	GARNET_REG_PSC_BSYLOG_CTRL,
	GARNET_REG_PSC_BSYLOG_CYCLE,
	GARNET_REG_PSC_BSYLOG_READ,
	GARNET_REG_PSC_RSV3,
	GARNET_REG_PSC_RSV4,
	GARNET_REG_PSC_VRAM_0_CNT_R,
	GARNET_REG_PSC_VRAM_0_CNT_W,
	GARNET_REG_PSC_VRAM_1_CNT_R,
	GARNET_REG_PSC_VRAM_1_CNT_W,
	GARNET_REG_PSC_P3D_GEO_CNT_R,
	GARNET_REG_PSC_P3D_TEX_CNT_R,
	GARNET_REG_PSC_P3D_CU_0_CNT_R,
	GARNET_REG_PSC_P3D_CU_0_CNT_W,
	GARNET_REG_PSC_P3D_CU_1_CNT_R,
	GARNET_REG_PSC_P3D_CU_1_CNT_W,
	GARNET_REG_PSC_PDC_0_CNT_R,
	GARNET_REG_PSC_PDC_1_CNT_R,
	GARNET_REG_PSC_PPF_CNT_R,
	GARNET_REG_PSC_PPF_CNT_W,
	GARNET_REG_PSC_PSC_0_CNT_W,
	GARNET_REG_PSC_PSC_1_CNT_W,
	GARNET_REG_PSC_NUM,
	
	GARNET_REG_PSC_MAX_BIT = (1u << 30)
} garnet_psc_reg_t;

#define GARNET_REG_PICA_BASE					0x00400000
#define GARNET_REG_PICA_SIZE					0x00002000

#define GARNET_REG_PDC_BEGIN					(GARNET_REG_PICA_BASE + 0x00000400)
#define GARNET_ADDR_PDC(x)						(((x) << 2) + GARNET_REG_PDC_BEGIN)
#define GARNET_REG_PDC_END						GARNET_ADDR_PDC(GARNET_REG_PDC_NUM)

#define GARNET_REG_PPF_BEGIN					(GARNET_REG_PICA_BASE + 0x00000c00)
#define GARNET_ADDR_PPF(x)						(((x) << 2) + GARNET_REG_PPF_BEGIN)
#define GARNET_REG_PPF_END						GARNET_ADDR_PPF(GARNET_REG_PPF_NUM)

#define GARNET_REG_P3D_BEGIN					(GARNET_REG_PICA_BASE + 0x00001000)
#define GARNET_REG_P3D_END						(GARNET_REG_PICA_BASE + 0x00002000)

#define GARNET_ADDR_P3D(x)						(((x) << 2) + GARNET_REG_P3D_BEGIN)
#define P3D_ADDR_GARNET(x)						(((x) - GARNET_REG_P3D_BEGIN) >> 2)

#define GARNET_REG_PSC_BEGIN					(GARNET_REG_PICA_BASE + 0x00000000)
#define GARNET_ADDR_PSC(x)						(((x) << 2) + GARNET_REG_PSC_BEGIN)
#define GARNET_REG_PSC_END						GARNET_ADDR_PSC(GARNET_REG_PSC_NUM)

