#pragma once

#define GEO_CI_BASE			0x200
#define GEO_LB_BASE			0x240
#define GEO_SYNC_BASE		0x248
#define GEO_VC_BASE			0x250
#define GEO_MUX0_BASE		0x258
#define GEO_MUX1_BASE		0x25c
#define GEO_RASIN_BASE		0x25e
#define GEO_VP_BASE			0x280
#define GEO_VP_CREG_BASE	0x290
#define GEO_VP_PRAM_BASE	0x29b
#define GEO_VP_SWZL_BASE	0x2a5
#define GEO_VP_LEN			0x30

enum base_geo_reg_addr_t{
	PA_CI_BASE_ADDRESS = GEO_CI_BASE,
	PA_RW_CI_ARRAY_SETTING0,
	PA_RW_CI_ARRAY_SETTING1,
	PA_RW_CI_ARRAY0_OFFSET,
	PA_RW_CI_ARRAY0_ATTR0,
	PA_RW_CI_ARRAY0_ATTR1,
	PA_RW_CI_ARRAY1_OFFSET,
	PA_RW_CI_ARRAY1_ATTR0,
	PA_RW_CI_ARRAY1_ATTR1,
	PA_RW_CI_ARRAY2_OFFSET,
	PA_RW_CI_ARRAY2_ATTR0,
	PA_RW_CI_ARRAY2_ATTR1,
	PA_RW_CI_ARRAY3_OFFSET,
	PA_RW_CI_ARRAY3_ATTR0,
	PA_RW_CI_ARRAY3_ATTR1,
	PA_RW_CI_ARRAY4_OFFSET,
	PA_RW_CI_ARRAY4_ATTR0,
	PA_RW_CI_ARRAY4_ATTR1,
	PA_RW_CI_ARRAY5_OFFSET,
	PA_RW_CI_ARRAY5_ATTR0,
	PA_RW_CI_ARRAY5_ATTR1,
	PA_RW_CI_ARRAY6_OFFSET,
	PA_RW_CI_ARRAY6_ATTR0,
	PA_RW_CI_ARRAY6_ATTR1,
	PA_RW_CI_ARRAY7_OFFSET,
	PA_RW_CI_ARRAY7_ATTR0,
	PA_RW_CI_ARRAY7_ATTR1,
	PA_RW_CI_ARRAY8_OFFSET,
	PA_RW_CI_ARRAY8_ATTR0,
	PA_RW_CI_ARRAY8_ATTR1,
	PA_RW_CI_ARRAY9_OFFSET,
	PA_RW_CI_ARRAY9_ATTR0,
	PA_RW_CI_ARRAY9_ATTR1,
	PA_RW_CI_ARRAY10_OFFSET,
	PA_RW_CI_ARRAY10_ATTR0,
	PA_RW_CI_ARRAY10_ATTR1,
	PA_RW_CI_ARRAY11_OFFSET,
	PA_RW_CI_ARRAY11_ATTR0,
	PA_RW_CI_ARRAY11_ATTR1,
	PA_RW_CI_INDEXARRAY_TYPE,
	PA_RW_CI_INDEXARRAY_COUNT,
	PA_RW_CI_VP_MODE,
	PA_RW_CI_DRAWARRAY_FIRST,
	PA_RW_CI_START_DRAW_ARRAY = 0x22e,
	PA_RW_CI_START_DRAW_ELEMENT,
	PA_RW_CI_CACHE_CLEAR = 0x231,
	PA_RW_CI_CONST_ATTR_NUMBER,
	PA_RW_CI_CONST_ATTR_DATA0,
	PA_RW_CI_CONST_ATTR_DATA1,
	PA_RW_CI_CONST_ATTR_DATA2,
	PA_RW_CI_CMDLIST0_LEN = 0x238,
	PA_RW_CI_CMDLIST1_LEN,
	PA_RW_CI_CMDLIST0_ADDR,
	PA_RW_CI_CMDLIST1_ADDR,
	PA_RW_CI_CMDLIST0_RUN,
	PA_RW_CI_CMDLIST1_RUN,
	PA_CI_LAST = PA_RW_CI_CMDLIST1_RUN,

	PA_LB_START = GEO_LB_BASE,
	PA_RW_LB_CLOCK_CONFIG = PA_LB_START,
	PA_RW_LB_BLANC,
	PA_RW_LB_ATTR_COUNT,
	PA_RW_LB_VP_CONNECT,
	PA_RW_LB_VP0_WRITE_DISABLE,
	PA_RW_LB_MULTIVP_WRITE,
	PA_LB_LAST = PA_RW_LB_MULTIVP_WRITE,

	PA_SYNC_START = GEO_SYNC_BASE,
	PA_RW_SYNC_CLOCK_CONFIG	= PA_SYNC_START,
	PA_RW_SYNC_BLANC,
	PA_RW_SYNC_ATTR_COUNT,
	PA_SYNC_LAST = PA_RW_SYNC_ATTR_COUNT,

	PA_VC_START = GEO_VC_BASE,
	PA_RW_VC_CLOCK_CONFIG = PA_VC_START,
	PA_RW_VC_ATTR_COUNT,
	PA_RW_VC_SEND_MODE,
	PA_RW_VC_DRAW_MODE,
	PA_RW_VC_SUBDIV_CONF,
	PA_VC_LAST = PA_RW_VC_SUBDIV_CONF,

	PA_MUX0_START = GEO_MUX0_BASE,
	PA_RW_MUX0_CLOCK_CONFIG	= PA_MUX0_START,
	PA_MUX0_LAST = PA_RW_MUX0_CLOCK_CONFIG,

	PA_MUX1_START = GEO_MUX1_BASE,
	PA_RW_MUX1_CLOCK_CONFIG	= PA_MUX1_START,
	PA_MUX1_LAST = PA_RW_MUX1_CLOCK_CONFIG,

	PA_RASIN_START = GEO_RASIN_BASE,
	PA_RW_RASIN_TRI_SETTING	= PA_RASIN_START,
	PA_RW_RASIN_START_ARRAY,
	PA_RASIN_LAST = PA_RW_RASIN_START_ARRAY,

	PA_VP_START = GEO_VP_BASE,
	PA_RW_VP_BOOL_REG = PA_VP_START,
	PA_RW_VP_INT_REG_TOP,
	PA_RW_VP_INT_REG_END = PA_RW_VP_INT_REG_TOP + 7,
	PA_RW_VP_MODE,
	PA_RW_VP_PROGRAM_ADDRESS,
	PA_RW_VP_INPUTMAP0,
	PA_RW_VP_INPUTMAP1,
	PA_RW_VP_OUTPUT_MASK,
	PA_RW_VP_START_TRIGGER,
	PA_RW_VP_PROGRAM_RENEWAL,
	PA_RW_VP_CONST_REG_ADDR = GEO_VP_CREG_BASE,
	PA_RW_VP_CONST_REG_TOP,
	PA_RW_VP_CONST_REG_END = PA_RW_VP_CONST_REG_TOP + 7,
	PA_RW_VP_PRAM_ADDR = GEO_VP_PRAM_BASE,
	PA_RW_VP_PRAM_TOP,
	PA_RW_VP_PRAM_END = PA_RW_VP_PRAM_TOP + 7,
	PA_RW_VP_SWIZZLE_ADDR = GEO_VP_SWZL_BASE,
	PA_RW_VP_SWIZZLE_TOP,
	PA_RW_VP_SWIZZLE_END = PA_RW_VP_SWIZZLE_TOP + 7,
	PA_VP_LAST = PA_RW_VP_SWIZZLE_END
};

typedef enum GARNET_PDC_DATA_FORMAT_T{
	GARNET_PDC_DATA_FORMAT_R8G8B8A8 = 0,
	GARNET_PDC_DATA_FORMAT_R8G8B8,
	GARNET_PDC_DATA_FORMAT_R5G6B5,
	GARNET_PDC_DATA_FORMAT_R5G5B5A1,
	GARNET_PDC_DATA_FORMAT_R4G4B4A4,
	
	GARNET_PDC_DATA_FORMAT_MAX_BIT = (1u << 30)
} garnet_pdc_data_format_t;
